# fly.toml app configuration file generated for amp-dev on 2023-09-16T15:18:11-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "amp-dev"
primary_region = "ord"
console_command = "/rails/bin/rails console"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
